#!/usr/bin/env bash
# Open /etc/passwd file

while IFS=: read -r username password userid groupid userinfo homedir shell; do
  # Print the formatted story for each user
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd

