#!/usr/bin/env bash
# Check if the log file exists

if [ ! -f apache-access.log ]; then
  echo "Log file not found!"
  exit 1
fi

# Parse, group, and sort the log data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'

