#!/usr/bin/env bash
# Dispalys the time for 12 hours and 50 minutes.
#  Displays hours from 0 to 12
#  Displays minutes from 1 to 50

hour=0

while [ $hour -le 12 ]
do
        echo "Hour: $hour"
        minute=1
        while [ $minute -le 59 ]
        do
                echo "$minute"
                (( minute++ ))
        done
        (( hour++ ))
done

