#!/usr/bin/env bash

# Open /etc/passwd file
while IFS=: read -r username _ userid _ _ homedir _; do
  # Print the username, user ID, and home directory path
  echo "$username:$userid:$homedir"
done < /etc/passwd

